### ISSUE TITLE
Wide review tracker

### ISSUE THREAD

**Issue by frivoal** [w3c/html-ruby#15]
This issue tracks horizontal and other reviews requested on this document, since its [restoration as a WD](https://www.w3.org/TR/2024/WD-html-ruby-extensions-20240507/).

Reviews requested should be listed here, and checked once the review has been completed. Requests for reviews that do not have a "completed" state (but are merely a heads up to some group) should be listed without a checkbox.

**Comment by frivoal** [comment]
* [ ] Privacy review: https://github.com/w3cping/privacy-request/issues/135
* [ ] Security review: https://github.com/w3c/security-request/issues/68
* [ ] Accessibility review: https://github.com/w3c/a11y-request/issues/83
* [ ] Internationalization review: https://github.com/w3c/i18n-request/issues/232

**Comment by frivoal** [comment]
* [ ] TAG Review: https://github.com/w3ctag/design-reviews/issues/959

**Comment by frivoal** [comment]
Based on the TPAC 2025 i18n WG meeting, the feedback by the i18n WG on the HTML ruby markup extension spec will be considered address once these two things are done:
* https://github.com/w3c/html-ruby/issues/17#issuecomment-3514569346
* https://github.com/w3c/html-ruby/issues/22#issuecomment-3514654333

**Comment by frivoal** [comment]
Added an Accessibility Considerations section, capturing key points of the [accessibility self review](https://github.com/w3c/html-ruby/issues/13): https://github.com/w3c/html-ruby/pull/27.

**Comment by frivoal** [comment]
Having given about 1.5 years to Security an Accessibility, without getting feedback (negative or otherwise), it seems safe to close this issue and to consider the review as not finding any particular issue.
